"""
Shared feature constants for CHILDES feature extraction/evaluation.
"""

# Function words used for counting/ratios (matches original extractor list).
FUNCTION_WORDS = {
    "the",
    "a",
    "an",
    "and",
    "but",
    "or",
    "because",
    "if",
    "when",
    "that",
    "this",
    "those",
    "these",
    "of",
    "for",
    "in",
    "on",
    "at",
    "to",
    "with",
    "as",
    "so",
    "by",
    "from",
    "up",
    "down",
    "not",
    "no",
    "don't",
    "do",
    "does",
    "did",
    "is",
    "am",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "can",
    "could",
    "should",
    "would",
    "will",
    "shall",
}

# Lightweight contraction expansions for function-word counting (does not alter tokens elsewhere).
CONTRACTION_MAP = {
    "don't": ["do", "not"],
    "dont": ["do", "not"],
    "didn't": ["did", "not"],
    "didnt": ["did", "not"],
    "doesn't": ["does", "not"],
    "doesnt": ["does", "not"],
    "can't": ["can", "not"],
    "cant": ["can", "not"],
    "couldn't": ["could", "not"],
    "shouldn't": ["should", "not"],
    "wouldn't": ["would", "not"],
    "won't": ["will", "not"],
    "wont": ["will", "not"],
    "wasn't": ["was", "not"],
    "wasnt": ["was", "not"],
    "weren't": ["were", "not"],
    "werent": ["were", "not"],
    "isn't": ["is", "not"],
    "isnt": ["is", "not"],
    "aren't": ["are", "not"],
    "arent": ["are", "not"],
    "ain't": ["is", "not"],
    "aint": ["is", "not"],
}
